### ISSUE TITLE
Bugs in the AD-MLP code

### ISSUE THREAD

**Issue by PointsCoder** [E2E-AD/AD-MLP#4]
I noticed a bug in this code. 

In the data_nuscene.pkl you provided, you are actually using the 3rd and the 7th ground truth waypoint coordinates as the acceleration and velocity value in Canbus.

This will cause severe label leakage and make your results much stronger.

I am wondering if there is a mistake in the release or you obtained your results with this data.
![截图 2023-09-17 15-27-04](https://github.com/E2E-AD/AD-MLP/assets/28640612/ff53b049-26cb-42b8-8082-2d56cc9ad8c5)

**Comment by E2E-AD** [comment]
We have reviewed the code and data again and have updated the revised training process at this link and on the GitHub website: https://pan.baidu.com/s/1IjN2pUUB35k2ScOitVsuGA?pwd=t4br. Thank you for your feedback.

**Comment by zhiqi-li** [comment]
VAD didn't use past trajs in their codebase, but AD-mlp used that. Based on table 1 in the paper, this information plays a key role in the final results. Why didn't you report the results w/o past trajs?

**Comment by xinshuoweng** [comment]
Thanks for your effort to double-check on this! I noticed that the released model and data pkl files (in May 2023) are still the old ones that have the GT leakage. Would you mind updating the released model files and data pkl file to reflect the newly trained model without GT leakage? Appreciate it!
